USER_TYPE_TEAM_LEADER = u'TEAM_LEADER'
USER_TYPE_TEAM_CHIEF = u'TEAM_CHIEF'
USER_TYPE_TEAM_WORKER = u'TEAM_WORKER'

USER_TYPES = (
    (USER_TYPE_TEAM_LEADER, u'Team Leader'),
    (USER_TYPE_TEAM_CHIEF, u'Team Chief'),
    (USER_TYPE_TEAM_WORKER, u'Team Worker')
)
