TASK_STATUS_TODO = u'TODO'
TASK_STATUS_IN_PROGRESS = u'IN_PROGRESS'
TASK_STATUS_DONE = u'DONE'

TASK_STATUSES = (
    (TASK_STATUS_TODO, u'Todo'),
    (TASK_STATUS_IN_PROGRESS, u'In progress'),
    (TASK_STATUS_DONE, u'Done')
)
