# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('TEAM_LEADER', 'Team Leader'), ('TEAM_CHIEF', 'Team Chief'), ('TEAM_WORKER', 'Team Worker')], default='TEAM_WORKER', max_length=256)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
