# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dev', to=settings.AUTH_USER_MODEL),
        ),
    ]
