# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170328_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_created',
        ),
    ]
